name: Dependency Review

on:
  pull_request:
    branches: [development, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    uses: AtyaLibraries/github-workflows/.github/workflows/dependency-review.yml@8b4d3932f62b03a9e191dca852282b3ce8a4f826 # v1
