name: Dependency Review

on:
  pull_request:
    branches: [development, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    uses: AtyaLibraries/github-workflows/.github/workflows/dependency-review.yml@f6190353bf05e780bd2b98a0980fe1a7b0e93a27 # v1
